; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200  ; Much slower, but more reliable
;upload_port = /dev/cu.usbserial-10 ;this is for direct usb connection
;monitor_port = /dev/cu.usbserial-10 ;this is for direct usb connection
upload_port = /dev/cu.usbserial-0001 ;this is for dongle connection
monitor_port = /dev/cu.usbserial-0001 ;this is for dongle connection
upload_protocol = esptool
upload_flags = 
;    --before=default_reset
;    --after=hard_reset
    --baud=115200

;ls /dev/cu.* to find the port
lib_deps =
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit Unified Sensor